### ISSUE TITLE
Errors with Starting EPS for 1st time

### ISSUE THREAD

**Issue by 05nelsonm** [chris-belcher/electrum-personal-server#104]
Following the README.md instructions, I renamed config.cfg_sample:
`$ mv config.cfg_sample config.cfg`

Made necessary alterations to config.cfg
additions = `++someting++` :
```
[bitcoin-rpc]
host = ++127.0.0.1++
port = 8332
#empty means look in the default location
datadir = ++/home/matthew/.bitcoin++
#if you dont want to use the .cookie method, uncomment to config u/p here
rpc_user = ++REMOVED++
rpc_password = ++REMOVED++

[electrum-server]
# 0.0.0.0 to accept connections from any IP
#127.0.0.1 to accept from only localhost
host = ++127.0.0.1++
port = 50002
```
Ran:
`$ pip3 install --user .`

got errors so I renamed `config.cfg` back to `config.cfg_sample`

re-ran and things were built, scripts were in ~/.local/bin

tried running:
`$ electrum-personal-server ~/electrum-personal-server-eps-v0.1.6/config.cfg`

and it shat out:
```
INFO:2019-04-17 15:34:54,633: Starting Electrum Personal Server
INFO:2019-04-17 15:34:54,633: Logging to /tmp/electrumpersonalserver.log
Traceback (most recent call last):
  File "/home/matthew/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/matthew/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 641, in main
    rpc_p = config.get("bitcoin-rpc", "rpc_password")
  File "/usr/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%Gn'
```

Tried various different suggestions, such as:

- Navigating  to the `~/.local/bin` directory and executing the command there.

- Adding `./` to the beginning of the command

- etc.

No juice. Assistance would be greatly appreciated!

**Comment by 05nelsonm** [comment]
Was my rpcuser & rpcpassword... had special characters in them.

removed special characters, worked.
