### ISSUE TITLE
ill-formed response error object: {'message': 'txid not found'}

### ISSUE THREAD

**Issue by adamcooper94** [chris-belcher/electrum-personal-server#110]
Hi,

I'm running Electrum 3.3.4 and electrum-personal-server v0.1.7 and getting the following error from electrum (having successfully run the rescan of bitcoind):

`$ electrum --oneserver --server localhost:50002:s`
```
QXcbConnection: XCB error: 8 (BadMatch), sequence: 492, resource id: 33554437, major code: 2 (ChangeWindowAttributes), minor code: 0
Traceback (most recent call last):
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/network.py", line 781, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/network.py", line 793, in get_merkle_for_transaction
    return await self.interface.session.send_request('blockchain.transaction.get_merkle', [tx_hash, tx_height])
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/interface.py", line 107, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/session.py", line 526, in send_request
    raise result
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/jsonrpc.py", line 715, in receive_message
    item, request_id = self._protocol.message_to_item(message)
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/jsonrpc.py", line 269, in message_to_item
    return cls._process_response(payload)
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/jsonrpc.py", line 216, in _process_response
    raise cls._error(code, message, False, request_id)
aiorpcx.jsonrpc.ProtocolError: (-32600, "ill-formed response error object: {'message': 'txid not found'}")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/util.py", line 910, in wrapper
    return await func(*args, **kwargs)
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/interface.py", line 289, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/interface.py", line 307, in run
    await self.open_session(ssl_context)
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/interface.py", line 407, in open_session
    await group.spawn(self.monitor_connection)
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 240, in __aexit__
    await self.join()
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 207, in join
    raise task.exception()
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/verifier.py", line 63, in _start_tasks
    await group.spawn(self.main)
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 240, in __aexit__
    await self.join()
  File "/home/ac/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 207, in join
    raise task.exception()
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/verifier.py", line 99, in _request_and_verify_single_proof
    merkle = await self.network.get_merkle_for_transaction(tx_hash, tx_height)
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/network.py", line 768, in make_reliable_wrapper
    raise success_fut.exception()
  File "/home/ac/.local/lib/python3.6/site-packages/electrum/network.py", line 783, in wrapper
    raise UntrustedServerReturnedError(original_exception=e)
electrum.network.UntrustedServerReturnedError: The server returned an error.
``` 
This occurs repeatedly after electrum tries and fails to synchronize.

I see the corresponding debug line in the /tmp/electrumpersonalserver.log:

```DEBUG:2019-04-27 18:50:23,859: <= {"error": {"message": "txid not found"}, "jsonrpc": "2.0", "id": 44}```

Any idea what the issue might be from?

**Comment by chris-belcher** [comment]
What else does it say in debug.log? Probably there is one txid being requested which causes this crash, can you tell which txid that is? and how does it end up being requested, it sounds weird since EPS only tells Electrum about txids it can know about.

**Comment by chris-belcher** [comment]
Did you find a solution for this? What was it? It's good to write what happened in case anyone else has the same problem.
