### ISSUE TITLE
ESP crashes at start seems it is because tx was dropped from mempool

### ISSUE THREAD

**Issue by tionlion** [chris-belcher/electrum-personal-server#120]
ESP is crashing on start after a pending receive tx was dropped from the mempool.

INFO:2019-05-17 19:40:02,650: Obtaining bitcoin addresses to monitor . . .
INFO:2019-05-17 19:41:04,029: Obtained list of addresses to monitor in 61.838687896728516sec
INFO:2019-05-17 19:41:04,029: Building history with 8000 addresses . . .
Traceback (most recent call last):
  File "/home/r/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/r/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 756, in main
    if not txmonitor.build_address_history(relevant_spks_addrs):
  File "/home/r/.local/lib/python3.6/site-packages/electrumpersonalserver/server/transactionmonitor.py", line 187, in build_address_history
    new_history_element = self.generate_new_history_element(tx, txd)
  File "/home/r/.local/lib/python3.6/site-packages/electrumpersonalserver/server/transactionmonitor.py", line 255, in generate_new_history_element
    True])
  File "/home/r/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line 96, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.server.jsonrpc.JsonRpcError: {'code': -5, 'message': 'No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.'}

**Comment by chris-belcher** [comment]
Thanks for the bug report.

**Comment by runjam1** [comment]
I try to run the file by clicking on the highlighted application and it immediately crashes. 
![Screenshot (75)](https://user-images.githubusercontent.com/42794700/58227378-6c6aca80-7cdf-11e9-934d-7bfa04080864.png)

**Comment by DriftwoodPalace** [comment]
@runjam1 
You need to create a copy of config.ini_sample rename it to config.ini and modify it with your information (your master public keys from Electrum etc). Then start the program by dragging config.ini on top of the application. For more detailed information, see: https://github.com/DriftwoodPalace/guides/blob/master/hodl-guide/hodl-guide_63_eps-win.md#modify-the-config-file

**Comment by chris-belcher** [comment]
Fixed in https://github.com/chris-belcher/electrum-personal-server/commit/8488d0b1032ea42850f983835665925938b50481
