### ISSUE TITLE
KeyError with Bitcoin Core 0.19.0rc1

### ISSUE THREAD

**Issue by jonas-ott** [chris-belcher/electrum-personal-server#152]
With 0.19.0rc1 the server stops with the following error after Electrum connected. Using 0.18.1 doesn't result in an error.

``Traceback (most recent call last):
  File "/home/jonas/.local/bin/electrum-personal-server", line 10, in <module>
    sys.exit(main())
  File "/home/jonas/.local/lib/python3.7/site-packages/electrumpersonalserver/server/common.py", line 759, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/jonas/.local/lib/python3.7/site-packages/electrumpersonalserver/server/common.py", line 494, in run_electrum_server
    broadcast_method)
  File "/home/jonas/.local/lib/python3.7/site-packages/electrumpersonalserver/server/common.py", line 276, in handle_query
    fee_rate = 1e8*details["fee"] // details["size"]
KeyError: `'size'``

**Comment by chris-belcher** [comment]
Thanks for the issue. The fix is in master https://github.com/chris-belcher/electrum-personal-server/commit/145cce2eb936bc74a18485177c8542ae5f2fd7d8 but there hasn't been a new release yet.
