### ISSUE TITLE
JsonRpcError: Verifying blocks

### ISSUE THREAD

**Issue by ln2max** [chris-belcher/electrum-personal-server#159]
When bitcoind is restarted while EPS is running:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 524, in run_electrum_server
    sock, addr = server_sock.accept()
  File "/usr/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 824, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 533, in run_electrum_server
    on_heartbeat_listening(txmonitor)
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 92, in on_heartbeat_listening
    txmonitor.check_for_updated_txes()
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/transactionmonitor.py", line 302, in check_for_updated_txes
    updated_scrhashes1 = self.check_for_new_txes()
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/transactionmonitor.py", line 442, in check_for_new_txes
    True])
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line 97, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.server.jsonrpc.JsonRpcError: {'code': -28, 'message': 'Verifying blocks...'}
```

**Comment by chris-belcher** [comment]
Has bitcoin core finished synchronizing?

**Comment by ln2max** [comment]
No, the error happens if Bitcoin Core is restarted while EPS is running, and EPS appears to handle the fact that bitcoind is still synchronizing by raising an exception.

Since EPS is a server application and is expected to be available at all times, it seems strange to require manual intervention if bitcoind restarts for some reason, when an exponential-backoff retry-loop (perhaps combined with a timeout) would be suitable for this situation (where we assume bitcoind will eventually be available in the future).

**Comment by chris-belcher** [comment]
Oh I see what you're saying. So it's the same as/similar to #39

**Comment by ln2max** [comment]
It also happens as a result of bitcoind quitting/restarting, but
this particular issue manifests itself in a slightly different way.
(This issue here could also occur if EPS is started while bicoind is
still starting up.)
