### ISSUE TITLE
Error broadcasting over TOR

### ISSUE THREAD

**Issue by filipszu** [chris-belcher/electrum-personal-server#176]
OS: Ubuntu 18.04
Python: 3.6.9

I get an error when broadcasting over TOR. TOR as a service is running correctly. 
My config.ini has:
`
broadcast_method = tor
`
I get an error in the log like so:
`INFO:2020-01-14 01:48:49,412: Broadcasting tx <<::tx_hash_removed::>> with broadcast method: tor
Traceback (most recent call last):
  File "/home/filipszu/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/filipszu/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 439, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/filipszu/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 160, in run_electrum_server
    protocol.handle_query(query)
  File "/home/filipszu/.local/lib/python3.6/site-packages/electrumpersonalserver/server/electrumprotocol.py", line 334, in handle_query
    peertopeer.tor_broadcast_tx(txhex, tor_hostport, network,
NameError: name 'peertopeer' is not defined
`

I think the issue is missing import statements in the electrumprotocol.py file

**Comment by chris-belcher** [comment]
Thanks for the issue. Pushed commit https://github.com/chris-belcher/electrum-personal-server/commit/7cc939b8ab2565e976d9983ca4108cc3e3157b11 to master branch which hopefully fixes this.
