### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by filipszu** [chris-belcher/electrum-personal-server#177]
I think after last night fix for https://github.com/chris-belcher/electrum-personal-server/issues/176
caused another problem. Now when I try to run I get:

`Traceback (most recent call last):
  File "/home/filipszu/.local/bin/electrum-personal-server", line 7, in <module>
    from electrumpersonalserver.server.common import main
  File "/home/filipszu/.local/lib/python3.6/site-packages/electrumpersonalserver/__init__.py", line 2, in <module>
    import electrumpersonalserver.server
  File "/home/filipszu/.local/lib/python3.6/site-packages/electrumpersonalserver/server/__init__.py", line 39, in <module>
    from electrumpersonalserver.server.electrumprotocol import (
  File "/home/filipszu/.local/lib/python3.6/site-packages/electrumpersonalserver/server/electrumprotocol.py", line 17, in <module>
    import electrumpersonalserver.server.peertopeer as peertopeer
AttributeError: module 'electrumpersonalserver' has no attribute 'server'`

**Comment by chris-belcher** [comment]
Hold on I'll try it myself on regtest

**Comment by chris-belcher** [comment]
This commit should fix it for real time this https://github.com/chris-belcher/electrum-personal-server/commit/db78fb9e2d819f80b7501c43d56d96b8c22f4237

Thanks for testing
