### ISSUE TITLE
electrum-personal-server fatal error when Electrum connect

### ISSUE THREAD

**Issue by dr3ex** [chris-belcher/electrum-personal-server#179]
Hello, when I start Electrum Personal Server 0.2.0 (with Bitcoin Core 0.19.0.1) and connect to it with Electrum 3.3.8 there is a fatal error:

```
INFO:2020-01-27 05:28:20,261: Obtaining bitcoin addresses to monitor . . .
INFO:2020-01-27 05:31:55,920: Obtained list of addresses to monitor in 216.5725507736206sec
INFO:2020-01-27 05:31:55,923: Building history with 6007 addresses . . .
INFO:2020-01-27 05:31:58,973: Found 87 txes. History built in 1.6346971988677979sec
INFO:2020-01-27 05:31:59,141: Starting electrum server
INFO:2020-01-27 05:31:59,141: Listening for Electrum Wallet on ('0.0.0.0', 50002)
INFO:2020-01-27 05:39:57,629: Electrum connected from ('192.168.0.10', 51135)
Traceback (most recent call last):
  File "/home/bitcoin/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/bitcoin/.local/lib/python3.5/site-packages/electrumpersonalserver/server/common.py", line 704, in main
    poll_interval_connected, certfile, keyfile)
  File "/home/bitcoin/.local/lib/python3.5/site-packages/electrumpersonalserver/server/common.py", line 447, in run_electrum_server
    txmonitor)
  File "/home/bitcoin/.local/lib/python3.5/site-packages/electrumpersonalserver/server/common.py", line 250, in handle_query
    fee_rate = 1e8*details["fee"] // details["size"]
KeyError: 'size'
```

Could someone help me how to fix this?

**Comment by chris-belcher** [comment]
Run `electrum-personal-server --version` to check the version you're using. It's likely you're not actually using version 0.2.0

**Comment by jodobear** [comment]
i'm getting this same error on eps0.1.7 with bitcoin core 0.19.0.1 and electrum 3.3.8

**Comment by chris-belcher** [comment]
@jodobear eps0.1.7 is out of date, the newest release has the fix, so update to eps0.2.0

@dr3ex Did you manage to fix the problem?

**Comment by jodobear** [comment]
eps-v0.2.0 works, no issues - thanks chris!
