### ISSUE TITLE
Bitcoin Core 0.20.0 required..

### ISSUE THREAD

**Issue by Cessaa** [chris-belcher/electrum-personal-server#194]
Hello, good day 
First of all thank you for your project

Can I work with different coins in the electrum-person-server ? Is it only over bitcoin ?

`vagrant@vagrant:~/electrum-personal-server$ electrum-personal-server config.ini
INFO:2020-05-10 08:52:47,686: Starting Electrum Personal Server 0.2.0
INFO:2020-05-10 08:52:47,687: Logging to /tmp/electrumpersonalserver.log
ERROR:2020-05-10 08:52:47,761: ValueError("JsonRpcError({'code': -32601, 'message': 'Method not found'},)",)
ERROR:2020-05-10 08:52:47,761: Descriptor related RPC call failed. Bitcoin Core 0.20.0 or higher required. Exiting..
vagrant@vagrant:~/electrum-personal-server$ 
`

**Comment by chris-belcher** [comment]
Only the master branch requires Bitcoin Core 0.20.0, as it's still under development. Most users should use a release: instead https://github.com/chris-belcher/electrum-personal-server/releases

As for altcoins, I don't know, I'm not involved in altcoins.

**Comment by Cessaa** [comment]
Thank you for your quick reply.
I downloaded your older versions but I got another error, why ? 

```
berkay@berkay-X:~/electrum-personal-server-eps-v0.1.5$ ./server.py 
2020-05-12 16:30:36,222654 [  LOG] Obtaining bitcoin addresses to monitor . . .
2020-05-12 16:30:37,344929 [  LOG] Obtained list of addresses to monitor in 1.1222271919250488sec
2020-05-12 16:30:37,344988 [  LOG] Building history with 200 addresses . . .
2020-05-12 16:30:37,352252 [  LOG] Found 0 txes. History built in 0.0014400482177734375sec
2020-05-12 16:30:37,352399 [  LOG] Starting electrum server
2020-05-12 16:30:37,352443 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50002)
2020-05-12 16:31:09,245796 [  LOG] Electrum connected from ('127.0.0.1', 59308)
2020-05-12 16:31:09,245912 [  LOG] Electrum wallet disconnected
2020-05-12 16:31:09,450305 [  LOG] Electrum connected from ('127.0.0.1', 59310)
Traceback (most recent call last):
  File "./server.py", line 572, in <module>
    main()
  File "./server.py", line 569, in main
    poll_interval_listening, poll_interval_connected, certfile, keyfile)
  File "./server.py", line 367, in run_electrum_server
    txmonitor)
  File "./server.py", line 236, in handle_query
    uptime = rpc.call("uptime", [])
  File "/home/berkay/electrum-personal-server-eps-v0.1.5/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32601, 'message': 'Method not found'}

```
This is the result of the curl

```
berkay@berkay-X:~$ curl localhost:50002
curl: (56) Recv failure: Connection reset by peer
berkay@berkay-X:~$ 
```

**Comment by chris-belcher** [comment]
That node doesn't seem to have the RPC call `uptime`, that's very weird. Are you definitely using Bitcoin Core?
