### ISSUE TITLE
Electrum EPS Server displays error message when connecting (error code 13)

### ISSUE THREAD

**Issue by RaulRider** [chris-belcher/electrum-personal-server#223]
Updated to v0.2.1.1 and I ran the same command as always (electrum-personal-server path/user123/...), I've checked the config.ini to find no mistakes and everything is normal as before the update.
connecting rpc via rpc_user and rpc_password
bot bitcoin node and eps on same device
bitcoin core v 0.20.1
tx index enabled, no pruning

Any clue on why this error code 13?

Thanks

```
INFO:2020-10-20 19:56:18,928: Obtaining bitcoin addresses to monitor . . .
INFO:2020-10-20 19:56:18,928: Importing 4 wallets and 0 watch-only addresses into the Bitcoin node
Traceback (most recent call last):
  File "/home/user123/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/user123/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 449, in main
    count=int(config.get("bitcoin-rpc", "initial_import_count")))
  File "/home/user123/.local/lib/python3.6/site-packages/electrumpersonalserver/server/deterministicwallet.py", line 29, in import_addresses
    rpc.call("importmulti", [watchonly_addr_param, {"rescan": False}])
  File "/home/user123/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line 123, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.server.jsonrpc.JsonRpcError: {'code': -13, 'message': 'Error: Please enter the wallet passphrase with walletpassphrase first.'}
```

**Comment by RaulRider** [comment]
Hi there!

This is yourself from the future!

The good thing about posting an issue in github is how well you'll feel when helping yourself to solve it.

Problem solved. 
The error was because I was using an encrypted wallet in bitcoin core.
I just closed that wallet and created an new one without encryption and back to normal.

Thanks Raul, I also hope this helps someone else out there
