### ISSUE TITLE
Installation fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by Liongrass** [chris-belcher/electrum-personal-server#252]
Hi,

As of very recently I am unable to start EPS. I suspected some issue with some package upgrade in Ubuntu 20.04.
Starting EPS with `electrum-personal-server .eps/config.ini` I get:

```INFO:2021-10-24 23:19:51,986: Displaying first 3 addresses of each master public key:
Traceback (most recent call last):
  File "/home/.local/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.7/site-packages/electrumpersonalserver/server/common.py", line 840, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "/home/.local/lib/python3.7/site-packages/electrumpersonalserver/server/common.py", line 629, in get_scriptpubkeys_to_monitor
    first_addrs = [hashes.script_to_address(s, rpc) for s in first_spks]
  File "/home/.local/lib/python3.7/site-packages/electrumpersonalserver/server/common.py", line 629, in <listcomp>
    first_addrs = [hashes.script_to_address(s, rpc) for s in first_spks]
  File "/home/.local/lib/python3.7/site-packages/electrumpersonalserver/server/hashes.py", line 76, in script_to_address
    return rpc.call("decodescript", [scriptPubKey])["addresses"][0]
KeyError: 'addresses
```

I also tried upgrading EPS to 0.2.2. Running the command `pip3 install --user` I get the error:

```Traceback (most recent call last):
  File "/home/loysan/.local/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
  File "/home/loysan/.local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/loysan/.local/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/loysan/.local/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/loysan/.local/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
```

I suspected it might be a broken package dependency, i reinstalled all python3/python3.7/python3.8 packages, including `python3-distutils` and `python3.8-distutils`. The package `python3.7-distutils` could not be found.

I understand this is more of a python problem than a EPS problem, but I can't figure out what EPS dependency I might be missing.

Suddenly, I can neither run EPS 0.2.1 nor install EPS 0.2.2

**Comment by chris-belcher** [comment]
Did you make any progress with this error?

Closing the issue for now, feel free to reopen

**Comment by Liongrass** [comment]
Yeah, sorry for the lack of reply. I've added `deprecatedrpc=addresses` to my config file and eps is running. Thanks again!
