### ISSUE TITLE
'This type of wallet does not support this command' error on startup

### ISSUE THREAD

**Issue by bisq-usr** [chris-belcher/electrum-personal-server#269]
BitcoinCore 23.0
EPS 0.2.3

Tried to install everything from scratch, new certs, new wallet in core, etc. Same config file I've ever used.
EPS shows the first 3 addresses of the xpub correctly, and then this happens. Any ideas? Thanks!

INFO:2022-05-07 19:41:26,850: Obtaining bitcoin addresses to monitor . . .
INFO:2022-05-07 19:41:26,850: Importing 1 wallets and 0 watch-only addresses into the Bitcoin node
Traceback (most recent call last):
  File "/home/sat/.local/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
  File "/home/sat/.local/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 481, in main
    deterministicwallet.import_addresses(rpc, relevant_spks_addrs,
  File "/home/sat/.local/lib/python3.8/site-packages/electrumpersonalserver/server/deterministicwallet.py", line 29, in import_addresses
    rpc.call("importmulti", [watchonly_addr_param, {"rescan": False}])
  File "/home/sat/.local/lib/python3.8/site-packages/electrumpersonalserver/server/jsonrpc.py", line 122, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.server.jsonrpc.JsonRpcError: {'code': -4, 'message': 'This type of wallet does not support this command'}

**Comment by chris-belcher** [comment]
The latest Bitcoin Core creates descriptor wallets by default, but EPS requires legacy wallets.

So try recreating the Bitcoin Core wallet but with descriptor wallets disabled. You can do that with the GUI or with the `createwallet` RPC call.

**Comment by chris-belcher** [comment]
@la841 see the solution here: https://github.com/chris-belcher/electrum-personal-server/issues/266#issuecomment-1109835511

**Comment by paulscode** [comment]
Hello, I am seeing the error message in the OP.  In my case I am using a public key from my Trezor T rather than from BitcoinCore, and EPS 0.2.4.  I've tried with 3 different account types in the Trezor suite.  First was a default SegWit (BIP84, P2WPKH, Bech32).  After reading this issue, I tried with a Legacy SegWit (BIP49, P2SH-P2WPKH, Base58) and then with a Legacy (BIP44, P2PKH, Base58), but both of those also gave the same message.

--EDIT--
Sorry, after re-reading the README.md again, I realized that even though I am adding my Trezor master public key under [master public keys], I still have to do the step to create a BitcoinCore wallet, and specify the parameter "wallet_filename = electrumpersonalserver" in the [bitcoin-rpc] section of EPS config.  In my case I am using the GUI, so the equivalent to the bitcoin-cli command in the documentation is:
File > Create Wallet
Set Wallet name to "electrumpersonalserver"
Check "Disable Private Keys" and "Make Blank Wallet"
Uncheck "Descriptor Wallet"
done

So, nothing new to see here :)
