### ISSUE TITLE
KeyError: 'fee' when starting EPS

### ISSUE THREAD

**Issue by Arns** [chris-belcher/electrum-personal-server#279]
My setup used to work just fine a few months back around April. I just tried to boot EPS up (with Bitcoin Core, Electrum Wallet) and I get the following error:

```
INFO:2022-07-18 20:03:25,779: Obtaining bitcoin addresses to monitor . . .
INFO:2022-07-18 20:03:27,273: Obtained list of addresses to monitor in 1.5081593990325928sec
INFO:2022-07-18 20:03:27,273: Building history with 2001 addresses . . .
INFO:2022-07-18 20:03:27,441: Found 17 txes. History built in 0.1614077091217041sec
INFO:2022-07-18 20:03:27,545: Synchronizing mempool . . .
Traceback (most recent call last):
  File "/home/keith/.local/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
  File "/home/keith/.local/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 494, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/keith/.local/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 121, in run_electrum_server
    mempool_sync.initial_sync(logger)
  File "/home/keith/.local/lib/python3.8/site-packages/electrumpersonalserver/server/mempoolhistogram.py", line 57, in initial_sync
    self.poll_update(-1)
  File "/home/keith/.local/lib/python3.8/site-packages/electrumpersonalserver/server/mempoolhistogram.py", line 111, in poll_update
    fee_rate = 1e8*mempool_tx["fee"] // mempool_tx["vsize"]
KeyError: 'fee'
```

**Comment by mikeyb233** [comment]
The element "fee" has been deprecated from the json object returned by getmempoolentry. See https://developer.bitcoin.org/reference/rpc/getmempoolentry.html

A new object "fees" contains the element "base" which should replace the previous "fee"

fees = mempool_tx["fees"]
fee_rate = 1e8*fees["base"] // mempool_tx["vsize"]

**Comment by jdpy19** [comment]
Running into this error as well. Has this been changed in a new version?

Currently running 
`electrum-personal-server 0.2.1.1`
`Bitcoin-Core 24.1`
