### ISSUE TITLE
JsonRpcError while starting EPS

### ISSUE THREAD

**Issue by griswaalt** [chris-belcher/electrum-personal-server#29]
I am trying to run EPS on an Odroid HC2 running a fully synced Bitcoin 0.16 full node. I have made the necessary configurations in the `config.cfg` file i.e. providing my master public keys and RPC credentials that are used in `bitcoin.conf`. However, when I try to launch the server using `./server.py` I get the following exception:

```$ ./server.py
Traceback (most recent call last):
  File "./server.py", line 473, in <module>
    main()
  File "./server.py", line 448, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 308, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/bitcoin/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32601, 'message': 'Method not found'}
```

Any idea what I could be missing? I know that my RPC credentials are correct as I am able to connect my Samourai wallet on my phone to the same full node.

**Comment by griswaalt** [comment]
Looks like enabling the wallet in the Bitcoin full node resolved this issue.
