### ISSUE TITLE
Set path for config.cfg when starting server.py

### ISSUE THREAD

**Issue by Stadicus** [chris-belcher/electrum-personal-server#3]
When starting `server.py` on startup with a systemd unit, the execution is handled by root and the command needs to specify the full path of both python and eps, e.g. 

```bash
[Unit]
Description=Electrum Personal Server
After=bitcoind.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 /home/bitcoin/electrum-personal-server/server.py

[Install]
WantedBy=multi-user.target
```

This gives the error message `Non-existant configuration file 'config.cfg'`, as the script assumes that it is started from within the installation directory.

```bash
$ sudo systemctl start eps.service
$ sudo systemctl status eps.service
● eps.service - Electrum Personal Server
   Loaded: loaded (/etc/systemd/system/eps.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Mar 30 01:21:02 RaspiBolt systemd[1]: Started Electrum Personal Server.
Mar 30 01:21:02 RaspiBolt python3[13963]: 01:21:02,712804 [  LOG] Non-existant configuration file 'config.cfg'
```

Is it possible to set the full path for the `config.cfg` on startup, or do you know of a better way to handle the automatic start with systemd on boot?

**Comment by chris-belcher** [comment]
I think the best way is to allow setting the full path to the config file

**Comment by chris-belcher** [comment]
I've just made this commit which does that https://github.com/chris-belcher/electrum-personal-server/commit/e5f868ad5e8a2feea63ffcf97ea24ad4c00fa514

You can run `./server --help` to get information and `python3 path/to/server.py path/to/config.cfg` will work.

**Comment by Stadicus** [comment]
Nice, the `config.cfg` is found. 

I get additional errors however, as the server eg. wants to write the `debug.log` to the current directory. 

Started from root directory:
```
bitcoin@RaspiBolt:/ $ /usr/bin/python3 /home/bitcoin/electrum-personal-server/server.py  /home/bitcoin/electrum-personal-server/config.cfg
Traceback (most recent call last):
  File "/home/bitcoin/electrum-personal-server/server.py", line 469, in <module>
    main()
  File "/home/bitcoin/electrum-personal-server/server.py", line 412, in main
    debug_fd = open("debug.log", "w")
PermissionError: [Errno 13] Permission denied: 'debug.log'
```

Started with `systemd` using user "root": the server is running, but the `debug.log` is written to the root directory.
```
admin@RaspiBolt:~ $ sudo systemctl start eps.service
admin@RaspiBolt:~ $ sudo systemctl status eps.service
● eps.service - Electrum Personal Server
   Loaded: loaded (/etc/systemd/system/eps.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-03-30 14:24:43 CEST; 4s ago
 Main PID: 5921 (python3)
   CGroup: /system.slice/eps.service
           └─5921 /usr/bin/python3 /home/bitcoin/electrum-personal-server/server.py /home/bitcoin/electrum-personal-server/config.cfg

Mar 30 14:24:43 RaspiBolt systemd[1]: Started Electrum Personal Server.

admin@RaspiBolt:~ $ cd /
admin@RaspiBolt:/ $ ls -la
drwxr-xr-x  21 root root   4096 Mar 30 14:24 .
drwxr-xr-x  21 root root   4096 Mar 30 14:24 ..
drwxr-xr-x   2 root root   4096 Mar 13 22:59 bin
drwxr-xr-x   4 root root   2560 Mar 29 17:39 boot
-rw-r--r--   1 root root 117730 Mar 30 14:31 debug.log
...
```

The `debug.log` shows some more errors:
```
admin@RaspiBolt:/ $ cat /debug.log
14:24:43,702457 [DEBUG] obtaining auth from rpc_user/pass
14:25:36,414234 [  LOG] Building history with 600 addresses
14:25:36,466093 [DEBUG] listtransactions skip=0 len(ret)=28
14:25:36,466353 [DEBUG] adding obtained tx=######################################
....
14:25:37,364525 [  LOG] Found # txes. History built in 0.6600961685180664sec
14:25:37,365544 [  LOG] Starting electrum server
14:25:37,365983 [  LOG] Listening for Electrum Wallet on ('0.0.0.0', 50002)
14:25:40,706460 [  LOG] IOError: FileNotFoundError(2, 'No such file or directory')
14:25:50,783347 [  LOG] IOError: FileNotFoundError(2, 'No such file or directory')
14:26:00,792536 [  LOG] IOError: FileNotFoundError(2, 'No such file or directory')
..... (about 40+ entries)
```

**Comment by Stadicus** [comment]
Here wo go!

```
20:25:52,194770 [DEBUG] current working directory is: /home/bitcoin/electrum-personal-server
20:25:52,199419 [DEBUG] obtaining auth from rpc_user/pass
20:26:44,638105 [  LOG] Starting electrum server
20:26:44,638950 [  LOG] Listening for Electrum Wallet on ('0.0.0.0', 50002)
20:26:45,362662 [  LOG] Electrum connected from ('192.168.0.241', 52031)
...
```

**Comment by chris-belcher** [comment]
Cool. I'll see if anyone else posts another bug/problem, if not then I'll tag a new release.
