### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by LeoBeb** [chris-belcher/electrum-personal-server#304]
When a client tries to connect to the server using TLS, the following error occurs:
```
Traceback (most recent call last):
  File "/usr/local/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/electrumpersonalserver/server/common.py", line 494, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/usr/local/lib/python3.12/dist-packages/electrumpersonalserver/server/common.py", line 147, in run_electrum_server
    sock = ssl.wrap_socket(sock, server_side=True,
           ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

This is because the wrap_socket() function was deprecated after Python 3.7.
I was able to fix this by replacing lines 147-149:
```
                sock = ssl.wrap_socket(sock, server_side=True,
                    certfile=certfile, keyfile=keyfile,
                    ssl_version=ssl.PROTOCOL_SSLv23)
```

With the following:
```
                context = ssl.SSLContext(ssl.PROTOCOL_TLS)
                context.load_cert_chain(certfile=certfile, keyfile=keyfile)
                sock = context.wrap_socket(sock, server_side=True)
```

After that I was able to successfully connect with my Electrum wallet.

**Comment by rwoskating-hash** [comment]
Confirming this is still an issue on Linux Mint 22.2 / Python 3.12.3. The suggested fix to use SSLContext works perfectly. For anyone on Mint 22, the file is located at ~/.local/lib/python3.12/site-packages/server/common.py
