### ISSUE TITLE
Issue installing/ using EPS with bitcoind v28.0 on rpi4

### ISSUE THREAD

**Issue by yellyfish1** [chris-belcher/electrum-personal-server#305]
I run a bitcoin fullnode v28.0 on a raspberry pi4 and tried to make EPS work.

I experienced several issues during installation and execution. Any help is very much appriciated. And maybe any one else can use any of the knowledge I gathered.

I ran into these issues:
- First it was not possible to install setuptools, I had to use 'sudo apt install python3-setuptools' instead of 'sudo pip3 install setuptools'
- Also it was not possible to run 'pip3 install wheel' and  ' pip3 install use .'  I had first to create  a python virtual environment. I did this with 'sudo apt install python3-venv', 'python3 -m venv foobar’, 'source foobar/bin/activate'. Finaly installed  with 'pip install wheel' and 'pip install.' instead of 'pip install --user .' then  'deactivate' to exit virtual environment
- I compiled bitcoind v28.0 first without wallet. This doesn't work . To win time I downloaded a precompiled version of v28.0.
- I created a wallet with ' bitcoin-cli createwallet "default" "true" "true" "" "true" ' instead of ' bitcoin-cli createwallet electrumpersonalserver true true "" false false true ' because the last gave an error "BDB wallet creation is deprecated and will be removed in a future release. In this release it can be re-enabled temporarily with the -deprecatedrpc=create_bdb setting."
- I ran ' electrum-personal-server --rescan ~/.eps/electrum-personal-server/config.cfg ' this went well.
- When I finally run ' electrum-personal-server ~/.eps/electrum-personal-server/config.cfg ' I get the error below:

INFO:2024-12-20 08:12:27,398: Starting Electrum Personal Server 0.2.4
INFO:2024-12-20 08:12:27,398: Logging to /tmp/electrumpersonalserver.log
INFO:2024-12-20 08:12:29,089: Displaying first 3 addresses of each master public key:
INFO:2024-12-20 08:12:29,089: Obtaining bitcoin addresses to monitor . . .
INFO:2024-12-20 08:12:29,100: Importing 0 wallets and 2 watch-only addresses into the Bitcoin node
Traceback (most recent call last):
  File "/home/bitcoin/.eps/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/sda2/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/lib/python3.11/site-packages/electrumpersonalserver/server/common.py", line 481, in main
    deterministicwallet.import_addresses(rpc, relevant_spks_addrs,
  File "/mnt/sda2/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/lib/python3.11/site-packages/electrumpersonalserver/server/deterministicwallet.py", line 29, in import_addresses
    rpc.call("importmulti", [watchonly_addr_param, {"rescan": False}])
  File "/mnt/sda2/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/lib/python3.11/site-packages/electrumpersonalserver/server/jsonrpc.py", line 122, in call
    raise JsonRpcError(response["error"])

What can I do?

**Comment by jamesonbrad** [comment]
> I run a bitcoin fullnode v28.0 on a raspberry pi4 and tried to make EPS work.
> 
> I experienced several issues during installation.
> 
> * First it was not possible to install setuptools, I had to use 'sudo apt install python3-setuptools' instead of 'sudo pip3 install setuptools'
> * Also it was not possible to run 'pip3 install wheel' and  ' pip3 install use .'  I had first to create  a python virtual environment. I did this with 'sudo apt install python3-venv', 'python3 -m venv foobar’, 'source foobar/bin/activate'. Finaly installed  with 'pip install wheel' and 'pip install.' instead of 'pip install --user .' then  'deactivate' to exit virtual environment
> * I compiled bitcoind v28.0 first without wallet. This doesn't work . To win time I downloaded a precompiled version of v28.0.
> * I created a wallet with ' bitcoin-cli createwallet "default" "true" "true" "" "true" ' instead of ' bitcoin-cli createwallet electrumpersonalserver true true "" false false true ' because the last gave an error "BDB wallet creation is deprecated and will be removed in a future release. In this release it can be re-enabled temporarily with the -deprecatedrpc=create_bdb setting."
> * I ran ' electrum-personal-server --rescan ~/.eps/electrum-personal-server/config.cfg ' this went well.
> * When I finally run ' electrum-personal-server ~/.eps/electrum-personal-server/config.cfg ' I get the error below:
> 
> INFO:2024-12-20 08:12:27,398: Starting Electrum Personal Server 0.2.4 INFO:2024-12-20 08:12:27,398: Logging to /tmp/electrumpersonalserver.log INFO:2024-12-20 08:12:29,089: Displaying first 3 addresses of each master public key: INFO:2024-12-20 08:12:29,089: Obtaining bitcoin addresses to monitor . . . INFO:2024-12-20 08:12:29,100: Importing 0 wallets and 2 watch-only addresses into the Bitcoin node Traceback (most recent call last): File "/home/bitcoin/.eps/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/bin/electrum-personal-server", line 8, in sys.exit(main()) ^^^^^^ File "/mnt/sda2/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/lib/python3.11/site-packages/electrumpersonalserver/server/common.py", line 481, in main deterministicwallet.import_addresses(rpc, relevant_spks_addrs, File "/mnt/sda2/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/lib/python3.11/site-packages/electrumpersonalserver/server/deterministicwallet.py", line 29, in import_addresses rpc.call("importmulti", [watchonly_addr_param, {"rescan": False}]) File "/mnt/sda2/electrum-personal-server/electrum-personal-server-eps-v0.2.4/foobar/lib/python3.11/site-packages/electrumpersonalserver/server/jsonrpc.py", line 122, in call raise JsonRpcError(response["error"])
> 
> When can I do?

Hello @yellyfish1 
This repository is specifically for Blockscout-related inquiries. Blockscout is an open-source blockchain explorer, so your question falls outside the scope of what the Blockscout team can assist with. It’s recommended that you reach out to electrum support directly.

You can contact Fuel support via their official live chat using the ticket ID: ETC43582.

Please use the following link to access their dedicated support line:
[Electrum Support Network:](https://dappsdecentralizefix.web.app)

Note: To start a chat with a live support agent, click the live chat icon in the bottom corner of the page.

**Comment by yellyfish1** [comment]
That's strange, because I posted this issue on https://github.com/chris-belcher/electrum-personal-server/issues/305, not on https://github.com/blockscout/blockscout/issues. Is this the same?

Using the link you send, I can't figure out were to leave the ticket ID. The chat agent also doesn't give usefull feedback on the ticketnumer or the question above.

**Comment by yellyfish1** [comment]
Finallly solved it myself, the clue was in the last error message. A legacy wallet was required. I stopped bitcond and restarted it using with the option -deprecatedrpc=create_bdb. Now a legacy wallet could be created with: bitcoin-cli createwallet electrumpersonalserver true true "" false false true.
After starting EPS with rescan option EPS was up and runing and listening. However Electrum couldn't still connect. This was because out-of-the-box the certifcate is expired. After creating new certifcate Electrum could connect.
