### ISSUE TITLE
EPS is crashing soon after starting

### ISSUE THREAD

**Issue by suvayu** [chris-belcher/electrum-personal-server#31]
This is what I see on the terminal:

    $ ./server.py
    02:26:53,102823 [  LOG] Obtaining bitcoin addresses to monitor . . .
    02:26:59,197439 [  LOG] Obtained list of addresses to monitor in 6.094537258148193sec
    02:26:59,197553 [  LOG] Building history with 600 addresses . . .
    02:26:59,422105 [  LOG] Found 8 txes. History built in 0.1979377269744873sec
    02:26:59,422328 [  LOG] Starting electrum server
    02:26:59,422415 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50002)
    Traceback (most recent call last):
      File "./server.py", line 309, in run_electrum_server
        sock, addr = server_sock.accept()
      File "/usr/lib64/python3.6/socket.py", line 205, in accept
        fd, addr = self._accept()
    socket.timeout: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "./server.py", line 534, in <module>
        main()
      File "./server.py", line 531, in main
        poll_interval_listening, poll_interval_connected, certfile, keyfile)
      File "./server.py", line 318, in run_electrum_server
        on_heartbeat_listening(txmonitor)
      File "./server.py", line 84, in on_heartbeat_listening
        txmonitor.check_for_updated_txes()
      File "/scratch/build/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 253, in check_for_updated_txes
        updated_scrhashes1 = self.check_for_new_txes()
      File "/scratch/build/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 402, in check_for_new_txes
        txid_list = [(tx["txid"], tx["address"]) for tx in ret]
      File "/scratch/build/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 402, in <listcomp>
        txid_list = [(tx["txid"], tx["address"]) for tx in ret]
    KeyError: 'address'

In the debug log, the final two lines are:

    02:27:29,451898 [DEBUG] on heartbeat listening
    02:27:29,452064 [DEBUG] listtransactions tx_request_count=2

I tried looking at the code, all I could tell was sometimes the RPC call at  [`transactionmonitor.py:395`](https://github.com/chris-belcher/electrum-personal-server/blob/master/electrumpersonalserver/transactionmonitor.py#L395) does not give a complete response.  Since I'm not familiar with the code, I did not dig further.

It was working fine until yesterday, when I added another address in the `master-public-keys` section.  Since this is a wallet with a few transactions in it, after the first run, I used the rescan script. All seemed to go as expected with Electrum.  I think I didn't notice the crashes earlier because `systemd` was restarting the process after every crash.  I noticed it when I saw the connection was failing/succeeding intermittently (the red/green status in the lower right corner of the Electrum window).

Please let me know if I should provide other info.

**Comment by chris-belcher** [comment]
Thanks for the bug report! This is an unexpected bug for me, it means the result of `listtransactions` sometimes doesn't have an `address` field(!)

Please do this now to get more information:

Open `transactionmonitor.py` and right before line 402 https://github.com/chris-belcher/electrum-personal-server/blob/master/electrumpersonalserver/transactionmonitor.py#L402 add this line:

`self.debug("txid_list_no_addr = " + str([tx for tx in ret if "address" not in tx]))`

Then run EPS again and wait for it to crash. Open the file `debug.log` and scroll to the bottom, there should be a line `txid_list_no_addr = [something]`.

Copy the `something` here so we can see this strange tx that doesn't have an address field, but be careful because it may contain privacy-sensitive information such as TXIDs, if so then just replace them with TXID-HERE.

**Comment by suvayu** [comment]
Here's the debug output:

    05:35:21,095867 [DEBUG] on heartbeat listening
    05:35:21,095988 [DEBUG] listtransactions tx_request_count=2
    05:35:21,097256 [DEBUG] txid_list_no_addr = [{'involvesWatchonly': True, 'account': '', \
      'category': 'send', 'amount': 0.0, 'vout': 1, 'fee': 0.002032, 'confirmations': 83, \
      'blockhash': '0000000000000000001ac0485d68d97e8761c2916f0b018f7a5ba892bbaa0920', \
      'blockindex': 311, 'blocktime': 1528708402, 'txid': 'TXID-HERE', 'walletconflicts': [], \
      'time': 1528708171, 'timereceived': 1528708171, 'bip125-replaceable': 'no', 'abandoned': False}]

**Comment by suvayu** [comment]
I thought I give you a little more context to the transaction so I checked, the transaction is going to a multisig address. If you need it, I wouldn't mind sharing more details privately.

**Comment by chris-belcher** [comment]
Thanks.

It's interesting that it says `amount: 0.0`. Is the transaction really sending zero bitcoins?

**Comment by chris-belcher** [comment]
OK. Thanks anyway. I think I know how to fix this crash bug.

**Comment by chris-belcher** [comment]
The commit https://github.com/chris-belcher/electrum-personal-server/commit/2a0d918ac4ac19037846935893807491c77da15d should hopefully fix this crash. Closing this issue, it can be opened again if the same thing comes up.

**Comment by suvayu** [comment]
Thank you!

**Comment by suvayu** [comment]
I am seeing this again, I think you missed one last time.

    Traceback (most recent call last):
      File "/scratch/build/bitcoin/electrum-personal-server/server.py", line 352, in run_electrum_server
        recv_data = sock.recv(4096)
      File "/usr/lib64/python3.6/ssl.py", line 950, in recv
        return self.read(buflen)
      File "/usr/lib64/python3.6/ssl.py", line 827, in read
        return self._sslobj.read(len, buffer)
      File "/usr/lib64/python3.6/ssl.py", line 589, in read
        v = self._sslobj.read(len)
    socket.timeout: The read operation timed out
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/scratch/build/bitcoin/electrum-personal-server/server.py", line 559, in <module>
        main()
      File "/scratch/build/bitcoin/electrum-personal-server/server.py", line 556, in main
        poll_interval_listening, poll_interval_connected, certfile, keyfile)
      File "/scratch/build/bitcoin/electrum-personal-server/server.py", line 366, in run_electrum_server
        on_heartbeat_connected(sock, rpc, txmonitor)
      File "/scratch/build/bitcoin/electrum-personal-server/server.py", line 97, in on_heartbeat_connected
        updated_scripthashes = txmonitor.check_for_updated_txes()
      File "/scratch/build/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 255, in check_for_updated_txes
        updated_scrhashes1 = self.check_for_new_txes()
      File "/scratch/build/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 409, in check_for_new_txes
        str([(t["txid"], t["address"]) for t in ret]))
      File "/scratch/build/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 409, in <listcomp>
        str([(t["txid"], t["address"]) for t in ret]))
    KeyError: 'address'

**Comment by chris-belcher** [comment]
Thanks.

Reopening because there should be a test for this.
