### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by marcosrdz** [chris-belcher/electrum-personal-server#42]
I am running Bitcoin Core 0.16.0 fully synced and Electrum personal server 0.1.3

Configured config.cfg to include my RPC user and pass, and added my master public key. As soon as I run server.py, I get this error:

2018-07-21 23:49:24,165209 [  LOG] Obtaining bitcoin addresses to monitor . . .
Traceback (most recent call last):
  File "server.py", line 559, in <module>
    main()
  File "server.py", line 526, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "server.py", line 384, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/bitcoin/eps/electrum-personal-server-eps-v0.1.3/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32601, 'message': 'Method not found'}

**Comment by chris-belcher** [comment]
That seems to be saying the rpc method `getaddressesbyaccount` doesn't exist.

That's strange, my own bitcoin core is version 0.16 and it has that method.

I read that soon Bitcoin Core will be removing that method and replacing it with `getaddressesbylabel` but I believe that won't be until the next release.

**Comment by marcosrdz** [comment]
Seems like these commands took it's place:

GetAccount: returns the name of the account associated with the given address.
GetBalance: gets the balance in decimal bitcoins across all accounts or for a particular account.

**Comment by chris-belcher** [comment]
Do you still get this error with the latest version of Electrum Personal Server? Recently it was updated to support 0.17's new `getaddressesbylabel` method.

**Comment by jvandrew** [comment]
I get the similar/same error, running EPS 0.1.5 and Bitcoin Core 0.16.3:

2018-10-04 14:28:17,749948 [  LOG] Obtaining bitcoin addresses to monitor . . .
Traceback (most recent call last):
  File "./server.py", line 388, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/bitcoin/electrum-personal-server/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32601, 'message': 'Method not found'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./server.py", line 572, in <module>
    main()
  File "./server.py", line 539, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 392, in get_scriptpubkeys_to_monitor
    if transactionmonitor.ADDRESSES_LABEL in rpc.call("listlabels", []):
  File "/home/bitcoin/electrum-personal-server/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32601, 'message': 'Method not found'}

**Comment by jvandrew** [comment]
I believe I figured this out. It was a stupid mistake on my part.

My bitcoin.conf file had the disablewallet parameter. This caused Bitcoin Core to consider all wallet-related RPC calls to not exist.
