### ISSUE TITLE
Getaddressesbyaccount depreciated in latest Bitcoin client

### ISSUE THREAD

**Issue by coinsmith** [chris-belcher/electrum-personal-server#48]
Error with latest Bitcoind build, depreciated 'getaddressesbyaccount', which has to be manually added to bitcoin.conf, after which electrum-personal-server works again. Output below. 

./server.py 
2018-08-13 01:23:29,699618 [  LOG] Obtaining bitcoin addresses to monitor . . .
Traceback (most recent call last):
  File "./server.py", line 559, in <module>
    main()
  File "./server.py", line 526, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 384, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/user/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'message': 'getaddressesbyaccount is deprecated and will be removed in V0.18. To use this command, start bitcoind with -deprecatedrpc=accounts.', 'code': -32}

**Comment by chris-belcher** [comment]
Thanks. Related to issue #22. I'll see how to transition to using labels instead of accounts.

**Comment by chris-belcher** [comment]
Moving discussion to the above mentioned issue, as this is essentially a duplicate.

The master branch now contains a fix.
