### ISSUE TITLE
Error when no addresses have been imported

### ISSUE THREAD

**Issue by ypmaw** [chris-belcher/electrum-personal-server#51]
In eps-v0.1.4, when running against bitcoind 0.17.0rc3 eps halts before importing addresses. A master public key is set in config.cfg, but no watch-only-addresses. 

```
$ ./server.py 
2018-09-05 12:45:53,406474 [  LOG] Obtaining bitcoin addresses to monitor . . .
Traceback (most recent call last):
  File "./server.py", line 388, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/opt/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32, 'message': 'getaddressesbyaccount is deprecated and will be removed in V0.18. To use this command, start bitcoind with -deprecatedrpc=accounts.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./server.py", line 568, in <module>
    main()
  File "./server.py", line 535, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 393, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]).keys())
  File "/opt/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -11, 'message': 'No addresses with label electrum-watchonly-addresses'}
```

**Comment by chris-belcher** [comment]
Thanks for the bug report.

**Comment by chris-belcher** [comment]
The crash is caused `getaddressesbylabel` not being a perfect replacement to `getaddressesbyaccount`. The former will crash if you give it a label that doesn't exist, while the latter just returns an empty list. Fix incoming.

**Comment by chris-belcher** [comment]
I fixed this crash and made a new bugfix release https://github.com/chris-belcher/electrum-personal-server/releases/tag/eps-v0.1.5

This only affects people who are setting up Electrum Personal Server for the first time.
