### ISSUE TITLE
bitcoind 0.17.0 error

### ISSUE THREAD

**Issue by 0xbytes** [chris-belcher/electrum-personal-server#57]
I updated bitcoind to 0.17.0. 
EPS had no issues with 0.17.0 until I deleted wallet.dat to refresh it with new master public keys.

After deleting wallet.dat, I stared EPS with
python3.6 server.py to populate the wallet with new address. I received an error from EPS right of the bat.
-----------------------------------------
python3.6 server.py
2018-10-05 13:56:31,693779 [  LOG] Obtaining bitcoin addresses to monitor . . .
Traceback (most recent call last):
  File "server.py", line 388, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/dietpi/A/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32, 'message': 'getaddressesbyaccount is deprecated and will be removed in V0.18. To use this command, start bitcoind with -deprecatedrpc=accounts.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 568, in <module>
    main()
  File "server.py", line 535, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "server.py", line 393, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]).keys())
  File "/home/dietpi/A/eps_bk/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -11, 'message': 'No addresses with label electrum-watchonly-addresses'}

**Comment by chris-belcher** [comment]
I think you're using an old version of EPS, before the fix to issue #51

**Comment by 0xbytes** [comment]
After updating the to the latest version solved the error.
