### ISSUE TITLE
'getaddressesbyaccount is deprecated and will be removed in V0.18.

### ISSUE THREAD

**Issue by MrPaz** [chris-belcher/electrum-personal-server#60]
Attempting to set up EPS, and ran into the following error.  I am running core 0.17.

```
paz@Unity:~/electrum-personal-server/eps$ ./server.py
2018-10-22 18:46:08,578297 [  LOG] Obtaining bitcoin addresses to monitor . . .
Traceback (most recent call last):
  File "./server.py", line 559, in <module>
    main()
  File "./server.py", line 526, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 384, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/paz/electrum-personal-server/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32, 'message': 'getaddressesbyaccount is deprecated and will be removed in V0.18. To use this command, start bitcoind with -deprecatedrpc=accounts.'}
```

**Comment by MrPaz** [comment]
Not sure if this is the place, or if I should open another issue.. but restarting my daemon with the deprecatedrpc=accounts flag, I get this error:

```
paz@Unity:~/electrum-personal-server/eps$ ./server.py
2018-10-22 20:58:11,531573 [  LOG] Obtaining bitcoin addresses to monitor . . .
2018-10-22 20:58:11,577435 [  LOG] Importing 0 wallets and 1 watch-only addresses into the Bitcoin node
2018-10-22 20:58:16,582085 [  LOG] Importing 1 addresses in total
[0%]... [10%]... [20%]... [30%]... [40%]... [50%]... [60%]... [70%]... [80%]... [90%]... Traceback (most recent call last):
  File "./server.py", line 559, in <module>
    main()
  File "./server.py", line 529, in main
    log)
  File "/home/paz/electrum-personal-server/eps/electrumpersonalserver/transactionmonitor.py", line 43, in import_addresses
    rpc.call("importaddress", [a, ADDRESSES_LABEL, False])
  File "/home/paz/electrum-personal-server/eps/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -5, 'message': 'Invalid Bitcoin address or script'}
```
I followed the set up directions best I could.  My master pub key is correct, however my test wallet is empty.  Do you see anything amiss here??  Thank you.


```
## Electrum Personal Server configuration file
## Comments start with #

[master-public-keys]
## Add electrum master public keys to this section
## Create a wallet in electrum then go Wallet -> Information to get the mpk

#any_name_works = xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF
EPS_test_wallet = zpub6nKH35n5Uk3dzBumrx3scrQAyGtqQuqjZBSrsPyYGBJq9RD8bhS9vybxbV15WGxCce9ZCpBcqZ47QfEovR42nFLpfWcEgp1AVhvWJzVETWo

# Multisig wallets use format `required-signatures [list of master pub keys]`
#multisig_wallet = 2 xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF


[watch-only-addresses]
## Add addresses to this section

#addr = 1DuqpoeTB9zLvVCXQG53VbMxvMkijk494n
# A space separated list is accepted
#my_test_addresses = 3Hh7QujVLqz11tiQsnUE5CSL16WEHBmiyR 1PXRLo1FQoZyF1Jhnz4qbG5x8Bo3pFpybz bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq
EPS_test_wallet = zpub6nKH35n5Uk3dzBumrx3scrQAyGtqQuqjZBSrsPyYGBJq9RD8bhS9vybxbV15WGxCce9ZCpBcqZ47QfEovR42nFLpfWcEgp1AVhvWJzVETWo

[bitcoin-rpc]
host = localhost
port = 8332
#empty means look in the default location
datadir = /media/paz/BITCOINNODE
#if you dont want to use the .cookie method, uncomment to config u/p here
rpc_user = myuser
rpc_password = mypw

#to be used with the multi-wallet feature
# see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md#multi-wallet-support
# empty means default file, for when using a single wallet file
wallet_filename =

# how often in seconds to poll for new transactions when electrum not connected
poll_interval_listening = 30
# how often in seconds to poll for new transactions when electrum is connected
poll_interval_connected = 5

# Parameters for dealing with deterministic wallets
# how many addresses to import first time, should be big because if you import too little you may have to rescan again
initial_import_count = 100
# number of unused addresses kept at the head of the wallet
gap_limit = 25


[electrum-server]
# 0.0.0.0 to accept connections from any IP
#127.0.0.1 to accept from only localhost
host = 0.0.0.0
port = 50002

# space-separated whitelist of IP addresses
# accepts CIDR notation eg 192.168.0.0/16 or 2a01:4f8:1f1::/120
# star (*) means all are accepted
# generally requires host binding (above) to be 0.0.0.0
ip_whitelist = *

#uses the default one, which is fine because by default nobody should be
# allowed to connect to your server or scan your packets
#to generate another certificate see https://github.com/spesmilo/electrum-server/blob/ce1b11d7f5f7a70a3b6cc7ec1d3e552436e54ffe/HOWTO.md#step-8-create-a-self-signed-ssl-cert
certfile = certs/cert.crt
keyfile = certs/cert.key
```

**Comment by MrPaz** [comment]
Nevermind about the question above, I believe I have it functioning properly now.  Just had to comment out my watch-only address, which was the same as my other, mpk address.

**Comment by chris-belcher** [comment]
Regarding your first error, that has been fixed in the latest version of EPS so you should update (unless I've missed something)

Regarding your second error, in the config file, you put a master public key in the [watch-only-addresses] section, only addresses should go in that section, not mpks.

**Comment by MrPaz** [comment]
ugh, you are correct, no problems with v0.1.5.  apologies and thanks for your help.  

and thank you for building this, what a great tool.
