### ISSUE TITLE
handle_query error when starting EPS

### ISSUE THREAD

**Issue by yunier2002** [chris-belcher/electrum-personal-server#79]
Hey guys,

Having some issues starting EPS on a windows machine in the python shell, bitcoin core 0.17 running and all transactions sync fine but getting the following error when starting, running EPS 1.5 as was easier to install, any help is appreciated it. Thanks

 2019-01-04 23:12:46,719218 [  LOG] Obtaining bitcoin addresses to monitor . . .
2019-01-04 23:13:03,721419 [  LOG] Obtained list of addresses to monitor in 16.960201501846313sec
2019-01-04 23:13:03,759418 [  LOG] Building history with 1000 addresses . . .
2019-01-04 23:13:04,642409 [  LOG] Found 23 txes. History built in 0.7589919567108154sec
2019-01-04 23:13:04,686408 [  LOG] Starting electrum server
2019-01-04 23:13:04,694408 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50002)
2019-01-04 23:13:06,468924 [  LOG] Electrum connected from ('127.0.0.1', 50762)
Traceback (most recent call last):
  File "C:\Users\Yunier\Documents\Electrum Personal Server\electrum-personal-server-eps-v0.1.5\server.py", line 572, in <module>
    main()
  File "C:\Users\Yunier\Documents\Electrum Personal Server\electrum-personal-server-eps-v0.1.5\server.py", line 569, in main
    poll_interval_listening, poll_interval_connected, certfile, keyfile)
  File "C:\Users\Yunier\Documents\Electrum Personal Server\electrum-personal-server-eps-v0.1.5\server.py", line 367, in run_electrum_server
    txmonitor)
  File "C:\Users\Yunier\Documents\Electrum Personal Server\electrum-personal-server-eps-v0.1.5\server.py", line 114, in handle_query
    method = query["method"]
KeyError: 'method'

**Comment by yunier2002** [comment]
Got it to work, thanks guys
