### ISSUE TITLE
Error after Electrum3.3.2 update ?

### ISSUE THREAD

**Issue by MrPaz** [chris-belcher/electrum-personal-server#81]
Used EPS last week, no problems.  Since then, I installed latest electrum update (v 3.3.2) and now getting the following error.  I'm on Windows.  After clicking run-server.bat, it seems to proceed as normal to 'Listening for Electrum Wallet on... ' then after I launch electrum, it errors.

```
2019-01-09 12:10:19,777666 [  LOG] Obtaining bitcoin addresses to monitor . . .
2019-01-09 12:10:23,011790 [  LOG] Obtained list of addresses to monitor in 3.234123945236206sec
2019-01-09 12:10:23,011790 [  LOG] Building history with 200 addresses . . .
2019-01-09 12:10:23,511764 [  LOG] Found 8 txes. History built in 0.4687166213989258sec
2019-01-09 12:10:23,511764 [  LOG] Starting electrum server
2019-01-09 12:10:23,511764 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50002)
2019-01-09 12:11:16,371829 [  LOG] Electrum connected from ('127.0.0.1', 64981)
Traceback (most recent call last):
  File "server.py", line 572, in <module>
    main()
  File "server.py", line 569, in main
    poll_interval_listening, poll_interval_connected, certfile, keyfile)
  File "server.py", line 367, in run_electrum_server
    txmonitor)
  File "server.py", line 114, in handle_query
    method = query["method"]
KeyError: 'method'
Press any key to continue . . .
```

any ideas?

**Comment by chris-belcher** [comment]
You need to update to the latest version 0.1.6, as one of the things it does is be compatible with the latest Electrum protocol version.

An alternative is to downgrade your Electrum software.

Same as #79

**Comment by MrPaz** [comment]
Silly me.  I have it working again.  Thanks!
