### ISSUE TITLE
Failed to build electrum-personal-server

### ISSUE THREAD

**Issue by Gav111n** [chris-belcher/electrum-personal-server#87]
I love the idea of EPS but I'm struggling to install - so this is not really a software issue - more a user issue, I guess.

I'm very inexperienced with Linux, but nonetheless decided to go that route to create my full node - using Ubuntu 18.04.

Latest Bitcoin Core (QT) - all fine, fully synced, running for months. I use an external HDD to hold the data. So the Bitcoin folder is not located in my home folder. The Bitcoin folder and all contents are on the HDD.

Running Bitcoin Core through Tor hidden service - all fine, working fine for weeks.

Electrum - latest version installed, connects to my Ledger, all fine.

Final step - install EPS - I've followed your step by step guide, which all makes sense. But I'm getting stuck at the install stage:

"Failed building wheel for electrum-personal-server"
"Failed to build electrum-personal-server"
"...failed with error code 1 in /tmp/pip-kkzx7ao9-build/"

I tried editing config.cfg, thinking that I might need to point EPS at my Bitoin folder, in the [bitcoin-rpc] section with this:

datadir = /media/gavin/Bitcoin

But I get the same failure.

I've got a copy of all the info displayed in terminal at the end of the install attempt.

Any thoughts? Or can anyone point me to a forum where I might look for help?

**Comment by chris-belcher** [comment]
Look in the file `/tmp/pip-kkzx7ao9-build/`, maybe there's useful information there.

**Comment by andreysmi** [comment]
i think you shouldn't rename config.cfg_sample as set in the instruction. thy it with original name.

**Comment by Gav111n** [comment]
Thanks both for the reply.

There is no file or folder /tmp/pip-kkzx7ao9-build/.  Perhaps this is created temporarily during installation and then removed at the end?

Below I paste the information shown in the CLI at the end of the installation attempt.

You may be correct andreysmi, because the info shows: error: "can't copy 'config.cfg_sample': doesn't exist or not a regular file"

I will try renaming "config.cfg" back to "config.cfg_sample" and see how that goes. Here's the info from CLI:


gavin@gavin-GB-BXBT-2807:~/electrum-personal-server-eps-v0.1.6$ pip3 install --user .
Processing /home/gavin/electrum-personal-server-eps-v0.1.6
Building wheels for collected packages: electrum-personal-server
  Running setup.py bdist_wheel for electrum-personal-server ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-kkzx7ao9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppgznomdfpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/electrumpersonalserver
  copying electrumpersonalserver/__init__.py -> build/lib/electrumpersonalserver
  creating build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/secp256k1_main.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/py2specials.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/transaction.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/__init__.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/secp256k1_deterministic.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/main.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/deterministic.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/py3specials.py -> build/lib/electrumpersonalserver/bitcoin
  copying electrumpersonalserver/bitcoin/secp256k1_transaction.py -> build/lib/electrumpersonalserver/bitcoin
  creating build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/jsonrpc.py -> build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/transactionmonitor.py -> build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/common.py -> build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/hashes.py -> build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/__init__.py -> build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/deterministicwallet.py -> build/lib/electrumpersonalserver/server
  copying electrumpersonalserver/server/merkleproof.py -> build/lib/electrumpersonalserver/server
  running egg_info
  creating electrum_personal_server.egg-info
  writing electrum_personal_server.egg-info/PKG-INFO
  writing dependency_links to electrum_personal_server.egg-info/dependency_links.txt
  writing entry points to electrum_personal_server.egg-info/entry_points.txt
  writing top-level names to electrum_personal_server.egg-info/top_level.txt
  writing manifest file 'electrum_personal_server.egg-info/SOURCES.txt'
  reading manifest file 'electrum_personal_server.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'doc/*.md'
  warning: no files found matching 'config.cfg_sample'
  writing manifest file 'electrum_personal_server.egg-info/SOURCES.txt'
  creating build/lib/electrumpersonalserver/certs
  copying electrumpersonalserver/certs/cert.crt -> build/lib/electrumpersonalserver/certs
  copying electrumpersonalserver/certs/cert.key -> build/lib/electrumpersonalserver/certs
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/electrumpersonalserver
  creating build/bdist.linux-x86_64/wheel/electrumpersonalserver/certs
  copying build/lib/electrumpersonalserver/certs/cert.crt -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/certs
  copying build/lib/electrumpersonalserver/certs/cert.key -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/certs
  creating build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/secp256k1_main.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/py2specials.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/transaction.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/__init__.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/secp256k1_deterministic.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/main.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/deterministic.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/py3specials.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/bitcoin/secp256k1_transaction.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/bitcoin
  copying build/lib/electrumpersonalserver/__init__.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver
  creating build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/jsonrpc.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/transactionmonitor.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/common.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/hashes.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/__init__.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/deterministicwallet.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  copying build/lib/electrumpersonalserver/server/merkleproof.py -> build/bdist.linux-x86_64/wheel/electrumpersonalserver/server
  running install_data
  creating build/bdist.linux-x86_64/wheel/electrum_personal_server-0.1.4.dev0.data
  creating build/bdist.linux-x86_64/wheel/electrum_personal_server-0.1.4.dev0.data/data
  creating build/bdist.linux-x86_64/wheel/electrum_personal_server-0.1.4.dev0.data/data/etc
  creating build/bdist.linux-x86_64/wheel/electrum_personal_server-0.1.4.dev0.data/data/etc/electrum-personal-server
  error: can't copy 'config.cfg_sample': doesn't exist or not a regular file
  
  ----------------------------------------
  Failed building wheel for electrum-personal-server
  Running setup.py clean for electrum-personal-server
Failed to build electrum-personal-server
Installing collected packages: electrum-personal-server
  Running setup.py install for electrum-personal-server ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-kkzx7ao9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p4w1kr2w-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/electrumpersonalserver
    copying electrumpersonalserver/__init__.py -> build/lib/electrumpersonalserver
    creating build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/secp256k1_main.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/py2specials.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/transaction.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/__init__.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/secp256k1_deterministic.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/main.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/deterministic.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/py3specials.py -> build/lib/electrumpersonalserver/bitcoin
    copying electrumpersonalserver/bitcoin/secp256k1_transaction.py -> build/lib/electrumpersonalserver/bitcoin
    creating build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/jsonrpc.py -> build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/transactionmonitor.py -> build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/common.py -> build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/hashes.py -> build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/__init__.py -> build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/deterministicwallet.py -> build/lib/electrumpersonalserver/server
    copying electrumpersonalserver/server/merkleproof.py -> build/lib/electrumpersonalserver/server
    running egg_info
    writing electrum_personal_server.egg-info/PKG-INFO
    writing dependency_links to electrum_personal_server.egg-info/dependency_links.txt
    writing entry points to electrum_personal_server.egg-info/entry_points.txt
    writing top-level names to electrum_personal_server.egg-info/top_level.txt
    reading manifest file 'electrum_personal_server.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'doc/*.md'
    warning: no files found matching 'config.cfg_sample'
    writing manifest file 'electrum_personal_server.egg-info/SOURCES.txt'
    creating build/lib/electrumpersonalserver/certs
    copying electrumpersonalserver/certs/cert.crt -> build/lib/electrumpersonalserver/certs
    copying electrumpersonalserver/certs/cert.key -> build/lib/electrumpersonalserver/certs
    running install_lib
    running install_data
    error: can't copy 'config.cfg_sample': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-kkzx7ao9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p4w1kr2w-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-kkzx7ao9-build/
gavin@gavin-GB-BXBT-2807:~/electrum-personal-server-eps-v0.1.6$

**Comment by Gav111n** [comment]
You are right andreysmi. The installation process is looking for "config.cfg_sample" and not "config.cfg".

I changed the file name back to "config.cfg_sample" and installation completed correctly.

I have been able to start the server without problem. In the terminal change directory to ~/.local/bin

I checked that the 2 scripts were present, with the ls command. Then entered "electrum-personal-server ~/electrum-personal-server-eps-v0.1.6/config.cfg_sample"

or whatever path points to the "config.cfg_sample" file. I hope this helps you with starting the server.

**Comment by sergeylats** [comment]
Sergey Leo

**Comment by athijssen** [comment]
Hi guys, I’m on Ubuntu 18.04.1 LTS and I’ve run into the same problems. I was also able to install the electrum-personal-server and electrum-personal-server-rescan scripts to ~/.local/bin after renaming config.cfg back to config.cfg_sample

Like andreysmi mentioned I got 
“Successfully installed electrum-personal-server-0.1.4.dev0”

However, when I go to ~/.local/bin and try to run “electrum-personal-server ~/electrum-personal-server-eps-v0.1.6/config.cfg_sample” I get 

“electrum-personal-server: command not found” 

Same for “electrum-personal-server-rescan”

Any ideas?

**Comment by Gav111n** [comment]
Hi Athijssen,

Be aware that I'm very much a linux 'learner' - but here's my thoughts:

Change directory so that you are in ~/.local/bin

Then do a "ls -l" command.

Are the scripts “electrum-personal-server" and “electrum-personal-server-rescan” actually there?

If so, what do the permissions show? Mine show -rwxr-xr-x . So mine have user and group and others ending x, so that the scripts are executable. If not then do a chmod to change permissions to make them executable.

The scripts rely on you having python3 installed - but I guess you must have that to have installed EPS successfully. I sounds like some kind of permission issue.

See how you get on.

**Comment by athijssen** [comment]
Hi Gavin,

Thanks for replying, I’m also still learning Linux and command line fun! 

Anyway yes the scripts are in that directory, they have the same permissions as yours and python3 is installed.. 

@chris-belcher can you help please?

**Comment by suvayu** [comment]
> However, when I go to ~/.local/bin and try to run “electrum-personal-server ~/electrum-personal-server-eps-v0.1.6/config.cfg_sample” I get
> 
> “electrum-personal-server: command not found”
> 
> Same for “electrum-personal-server-rescan”

You do not have `~/.local/bin` in your `PATH`.  You can still execute the script by calling it with the full/relative path.  E.g. from inside that directory, you can call it as `./electrum-personal-server`, or from your home directory you can call as `~/.local/bin/electrum-personal-server`.  Note the leading path elements.

**Comment by 05nelsonm** [comment]
trying to install EPS, but it's throwing errors when I try to execute 'electrum-personal-server /path/to/config.cfg' , as outlined in the README.md

```
Errors:
matthew@Ubuntu-Desktop:~$ electrum-personal-server ~/eps-v0.1.6/config.cfg
INFO:2019-04-17 14:56:23,670: Starting Electrum Personal Server
INFO:2019-04-17 14:56:23,670: Logging to /tmp/electrumpersonalserver.log
Traceback (most recent call last):
  File "/home/matthew/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/matthew/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 641, in main
    rpc_p = config.get("bitcoin-rpc", "rpc_password")
  File "/usr/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%Gn'

```
Does the same thing if I input command with ./ while in the bin directory, or not. Still the same errors. Any suggestions?

**Comment by suvayu** [comment]
This is a separate issue. You have now successfully installed EPS, but you are providing it with a malformed config file. Could you please close this issue, and open a separate issue about the config file?

Please note: **do not** blindly post bits of your config file asking for help. You run the risk of inadvertently exposing private details about yourself.

**Comment by 05nelsonm** [comment]
> This is a separate issue. You have now successfully installed EPS, but you are providing it with a malformed config file. Could you please close this issue, and open a separate issue about the config file?
> 
> Please note: **do not** blindly post bits of your config file asking for help. You run the risk of inadvertently exposing private details about yourself.

copy, on it.
