### ISSUE TITLE
Crash on block reorg

### ISSUE THREAD

**Issue by fivepiece** [chris-belcher/electrum-personal-server#9]
When an electrum client is connected, a block reorg causes EPS to crash with error :
```
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -8, 'message': 'Block height out of range'}
```

How to reproduce :

1. mine a few blocks
2. launch EPS
3. launch electrum
4. initiate `invalidateblock <current block hash>` with `bitcoin-cli`
5. mine a single block

EPS will crash with log :

```
20:23:26,880314 [  LOG] Building history with 200 addresses
20:23:26,893473 [  LOG] Found 0 txes. History built in 0.002653360366821289sec
20:23:26,893597 [  LOG] Starting electrum server
20:23:26,893667 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50012)
20:23:39,616938 [  LOG] Electrum connected from ('127.0.0.1', 51648)
20:23:39,618929 [  LOG] Electrum wallet disconnected
20:23:39,829962 [  LOG] Electrum connected from ('127.0.0.1', 51650)
Traceback (most recent call last):
  File "p2pkh/server.py", line 485, in <module>
    main()
  File "p2pkh/server.py", line 482, in main
    poll_interval_connected, certfile, keyfile)
  File "p2pkh/server.py", line 302, in run_electrum_server
    txmonitor)
  File "p2pkh/server.py", line 152, in handle_query
    blockhash = rpc.call("getblockhash", [query["params"][0]])
  File "/home/user/software/crypto/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'message': 'Block height out of range', 'code': -8}
```

The crash doesn't happen if an electrum client is not connected to the server.

**Comment by chris-belcher** [comment]
So looks like Electrum is requesting a block height that is out of range because of the reorg.

Maybe we should just return an empty dict at that point? Any idea what ElectrumX does when there's a reorg?

**Comment by fivepiece** [comment]
Doesn't crash anymore with
```diff
diff --git a/server.py b/server.py
--- a/server.py
+++ b/server.py
@@ -149,7 +149,13 @@ def handle_query(sock, line, rpc, txmonitor):
         new_bestblockhash, header = get_current_header(rpc)
         send_response(sock, query, header)
     elif method == "blockchain.block.get_header":
-        blockhash = rpc.call("getblockhash", [query["params"][0]])
+        requested_block_num = query["params"][0]
+        our_block_count = rpc.call("getblockcount", [])
+        if requested_block_num <= our_block_count:
+            blockhash = rpc.call("getblockhash", [requested_block_num])
+        else:
+            # client requested a block out of range
+            blockhash = rpc.call("getblockhash", [our_block_count])
         header = get_block_header(rpc, blockhash)
         send_response(sock, query, header)
     elif method == "blockchain.block.get_chunk":
```
but then we crash with
```
21:36:32,669225 [  LOG] Building history with 200 addresses
21:36:32,681944 [  LOG] Found 0 txes. History built in 0.002523183822631836sec
21:36:32,682054 [  LOG] Starting electrum server
21:36:32,682122 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50012)
21:36:38,705527 [  LOG] Electrum connected from ('127.0.0.1', 58930) 
21:36:38,707663 [  LOG] Electrum wallet disconnected 
21:36:38,919857 [  LOG] Electrum connected from ('127.0.0.1', 58932)  
21:37:01,044076 [  LOG] Found new tx: {'fee': 3800, 'tx_hash': '8bb95b90ab61e485a7f801aae0b3fb46d47db830f4a3c46e9697d41271946863', 'height': 0}
21:37:06,083202 [  LOG] A transaction confirmed: 8bb95b90ab61e485a7f801aae0b3fb46d47db830f4a3c46e9697d41271946863
21:37:21,197129 [  LOG] Electrum wallet disconnected
21:37:21,406236 [  LOG] Electrum connected from ('127.0.0.1', 59960)
Traceback (most recent call last): 
  File "p2pkh/server.py", line 192, in handle_query
 result = rpc.call("sendrawtransaction", [query["params"][0]])
  File "/home/esh/software/crypto/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 59, in call
 raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -27, 'message': 'transaction already in block chain'}
  
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):  
  File "p2pkh/server.py", line 491, in <module> 
 main() 
  File "p2pkh/server.py", line 488, in main  
 poll_interval_connected, certfile, keyfile)
  File "p2pkh/server.py", line 308, in run_electrum_server 
 txmonitor)
  File "p2pkh/server.py", line 194, in handle_query 
 result = e.message
AttributeError: 'JsonRpcError' object has no attribute 'message'
```
which is fixed by
```diff
diff --git a/server.py b/server.py
--- a/server.py
+++ b/server.py
@@ -185,7 +185,7 @@ def handle_query(sock, line, rpc, txmonitor):
         try:
             result = rpc.call("sendrawtransaction", [query["params"][0]])
         except JsonRpcError as e:
-            result = e.message
+            result = str(e)
         debug("tx broadcast result = " + str(result))
         send_response(sock, query, result)
     elif method == "mempool.get_fee_histogram":
```
that returns the error to electrum, but still it can't see that the transaction was confirmed and still shows it as 0-conf and "Local"

**Comment by fivepiece** [comment]
I realized my thinking is wrong.  Obviously there's not going to be a single block reorg at the tip.  We don't throw away the current tip in favor of another one, but if there is a longer chain that overwrites our tip then we will.

Essentially I'm changing step (5) from OP to mine two blocks instead of a single one, so now we have :

1. mine a few blocks
2. launch EPS
3. launch electrum
4. initiate invalidateblock <current block hash> with bitcoin-cli
5. mine two blocks

This is an actual scenario that could happen in our node.  The change to `handle_query()` is not needed anymore.  Electrum correctly requests the next block from us as it can tell there was a reorg, but still there's the issue with the transaction becoming "Local" even though it's already in the chain.
Restarting electrum fixes it, changing the transaction state from Local to it actual confirmation count.

**Comment by fivepiece** [comment]
Another related crash, when a small block reorg happened and the once confirmed transaction is not in the new chain, electrum will request EPS for `blockchain.transaction.get_merkle`.
EPS then does:

https://github.com/chris-belcher/electrum-personal-server/blob/e86e946ecb331ab3b6b3debe18e7a7d4c06bfc6c/server.py#L110-L114
But if the transaction is not confirmed (or replaced) then it will not have a `"blockhash"` value, causing :
```
18:58:28,670434 [  LOG] Building history with 200 addresses
18:58:28,690061 [  LOG] Found 2 txes. History built in 0.009072303771972656sec
18:58:28,690172 [  LOG] Starting electrum server
18:58:28,690242 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50012)
18:58:32,906712 [  LOG] Electrum connected from ('127.0.0.1', 57676)
Traceback (most recent call last):
  File "p2pkh/server.py", line 489, in <module>
    main()
  File "p2pkh/server.py", line 486, in main
    poll_interval_connected, certfile, keyfile)
  File "p2pkh/server.py", line 306, in run_electrum_server
    txmonitor)
  File "p2pkh/server.py", line 118, in handle_query
    core_proof = rpc.call("gettxoutproof", [[txid], tx["blockhash"]])
KeyError: 'blockhash'
```
In my case the transaction was indeed unconfirmed but still valid, I added :
```python
elif method == "blockchain.transaction.get_merkle":
        txid = query["params"][0]
        try:
            tx = rpc.call("gettransaction", [txid])
            if "blockhash" not in tx:
                # this transaction is unconfirmed or has been replaced
                raise ValueError
            core_proof = rpc.call("gettxoutproof", [[txid], tx["blockhash"]])
```
which caused the transaction in electrum to goback to unconfirmed state, and later on to confirmed when a block did include it, but there might be more to it like maybe checking if `tx["confirmations"]` is `-1`?

**Comment by fivepiece** [comment]
I just got the
```
Traceback (most recent call last):
  File "p2pkh/server.py", line 488, in <module>
    main()
  File "p2pkh/server.py", line 485, in main
    poll_interval_connected, certfile, keyfile)
  File "p2pkh/server.py", line 305, in run_electrum_server
    txmonitor)
  File "p2pkh/server.py", line 155, in handle_query
    blockhash = rpc.call("getblockhash", [query["params"][0]])
  File "/home/esh/software/crypto/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -8, 'message': 'Block height out of range'}
```
error and crash again after removing the code to return the current hash.
I guess we should be handling it somehow like in
https://github.com/kyuupichan/electrumx/blob/02ab8e5742688196d966c1e554e2ea98fca8e824/server/controller.py#L300-L305

**Comment by chris-belcher** [comment]
I just tested out of range calls for `blockchain.block.get_header` on an electrum server, which matches what that ElectrumX code says.

```{u'jsonrpc': u'2.0', u'id': 2, u'result': {u'nonce': 2962020205, u'prev_block_hash': u'00000000000000000004819b7cc7ae212c80dc9b8e115b6f0bb920c4834df664', u'timestamp': 1523202090, u'merkle_root': u'46b565a2fe665edeff2a15fc0fbacd4ff2b6b268026d9779897006298f865a40', u'block_height': 517241, u'version': 536870912, u'bits': 391129783}}
{u'jsonrpc': u'2.0', u'id': 3, u'result': {u'nonce': 3046781007, u'prev_block_hash': u'0000000000000000003d1c0fa13f9373f5471d4ab46722b4f8b37dddb06fbcce', u'timestamp': 1523202606, u'merkle_root': u'a9949a1e8338e50b0cb20da98160ef18f9beff437b4b09f6d07bff62856a5fbc', u'block_height': 517242, u'version': 536870912, u'bits': 391129783}}
{u'jsonrpc': u'2.0', u'id': 4, u'result': {u'nonce': 2310832361, u'prev_block_hash': u'00000000000000000007286a3e30b5e3ecab56e12c8a364474df1b6dbf245564', u'timestamp': 1523203050, u'merkle_root': u'cdf0fa0a87b15bfc445792f186a3bbe6b729b34545ed8ac6f080266ffb979037', u'block_height': 517243, u'version': 536870912, u'bits': 391129783}}
{u'jsonrpc': u'2.0', u'id': 5, u'error': {u'message': u'height 517,244 out of range', u'code': -1}}
{u'jsonrpc': u'2.0', u'id': 6, u'error': {u'message': u'height 517,245 out of range', u'code': -1}}```

**Comment by chris-belcher** [comment]
Hopefully fixed the crash bug from the out-of-range header requests here https://github.com/chris-belcher/electrum-personal-server/commit/c8dbdd8bd4b0c37e210e174a42c0daa7b5883235

**Comment by fivepiece** [comment]
I was able to trigger a crash with using the same flow, but probably due to misnamed variables
```
Traceback (most recent call last):
  File "p2pkh/server.py", line 159, in handle_query
    blockhash = rpc.call("getblockhash", [height])
  File "/home/user/software/crypto/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -8, 'message': 'Block height out of range'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "p2pkh/server.py", line 496, in <module>
    main()
  File "p2pkh/server.py", line 493, in main
    poll_interval_connected, certfile, keyfile)
  File "p2pkh/server.py", line 313, in run_electrum_server
    txmonitor)
  File "p2pkh/server.py", line 165, in handle_query
    send_error(sock, query["id"], error)
  File "p2pkh/server.py", line 75, in send_error
    sock.sendall(json.dumps(query).encode('utf-8') + b'\n')
NameError: name 'query' is not defined
```

**Comment by chris-belcher** [comment]
Doh. Hopefully fixed that with the latest commit.

Eventually I'll get this regtest thing set up myself, so I can test without bothering you. Thanks for doing this.

**Comment by fivepiece** [comment]
Yep, was able to trigger the error, electrum reconnected and became synced with the new tip.

```
20:42:04,102220 [DEBUG] <= {"jsonrpc": "2.0", "error": {"message": "height 442 out of range", "code": -1}, "id": 139}
20:42:04,104830 [  LOG] Electrum wallet disconnected
20:42:04,314296 [  LOG] Electrum connected from ('127.0.0.1', 49610)
20:42:04,417965 [DEBUG] => {"params": [], "id": 140, "method": "blockchain.headers.subscribe"}
...
```

**Comment by chris-belcher** [comment]
That might just be normal behaviour?

**Comment by fivepiece** [comment]
Yea I think so.  It's basically trying another server, but since we only point it to ours it just reconnects

**Comment by chris-belcher** [comment]
Maybe Electrum wallet itself doesn't handle reorgs that well. It's not a very big mishandling but still.

**Comment by chris-belcher** [comment]
Committed code which checks for reorgs https://github.com/chris-belcher/electrum-personal-server/commit/44cf99613314e673457c3e4b14fd41f5358e8d09

There is a new function `check_for_reorganizations()` and a new list `self.reorganizable_txes`.

Tested it as much as I can myself with regtest, it's actually surprisingly hard to test. Will write automated tests soon.

Electrum wallet itself actually doesn't handle reorgs very well. Restarting Electrum always results with it displaying the correct history.

**Comment by chris-belcher** [comment]
Added many new tests to test the reorg-checking code https://github.com/chris-belcher/electrum-personal-server/commit/5b71d929988cf99a6ff2d5595218e4419c9cc620

Closing this issue now as I believe all the crashes have been fixed, it can be reopened if required.
